import Foundation
import KoardSDK

extension KoardTransaction {
    public static var mockApprovedTransaction: KoardTransaction {
        .init(
            transactionId: "txn_000123456",
            eventId: "event_001abc",
            mid: "mid_123",
            tid: "tid_123",
            processorMid: "proc_mid_abc",
            processorTid: "proc_tid_def",
            accountId: "acct_789",
            deviceId: "device_xyz",
            processor: "Stripe",
            gateway: "DemoGateway",
            currency: "USD",
            locationId: "loc_321",
            gatewayTransactionId: "gw_txn_demo123",
            subtotal: 1500,
            tipAmount: 300,
            tipType: .percentage,
            taxAmount: 120,
            taxRate: 8,
            totalAmount: 1920,
            surchargeApplied: true,
            surchargeAmount: 30,
            surchargeRate: 2.0,
            refunded: 0,
            reversed: 0,
            ownerId: "owner_999",
            parentAccountIds: ["acct_parentA", "acct_parentB"],
            createdAt: Int(Date().timeIntervalSince1970 * 1000),
            status: .captured,
            statusReason: nil,
            paymentMethod: "card",
            cardType: "credit",
            cardBrand: "Visa",
            card: "**** 4242",
            additionalDetails: ["note": AnyCodable("Test transaction for preview")],
            gatewayTransactionResponse: .approvedGatewayTransactionResponse,
            processorResponseCode: "00",
            processorResponseMessage: "Approved",
            transactionType: "sale",
            appleTransactionId: "apple_txn_demo001",
            readerIdentifier: "reader_456",
            surchargeDisclosure: "A 2% surcharge was applied",
            surchargeAllowed: true,
            surchargePercentage: 2.0
        )
    }

    public static var mockDeclinedTransction: KoardTransaction {
        .init(
            transactionId: "txn_declined_001",
            eventId: "event_declined_abc",
            mid: "mid_declined",
            tid: "tid_declined",
            processorMid: "proc_mid_declined",
            processorTid: "proc_tid_declined",
            accountId: "acct_declined",
            deviceId: "device_declined",
            processor: "Stripe",
            gateway: "DeclineGateway",
            currency: "USD",
            locationId: "loc_decline",
            gatewayTransactionId: "gw_declined_001",
            subtotal: 1000,
            tipAmount: 0,
            tipType: nil,
            taxAmount: 80,
            taxRate: 8,
            totalAmount: 1080,
            surchargeApplied: false,
            surchargeAmount: nil,
            surchargeRate: nil,
            refunded: 0,
            reversed: 0,
            ownerId: "owner_declined",
            parentAccountIds: ["parent1"],
            createdAt: Int(Date().timeIntervalSince1970 * 1000) - 3600000,
            status: .declined,
            statusReason: "Insufficient funds",
            paymentMethod: "card",
            cardType: "debit",
            cardBrand: "Mastercard",
            card: "**** 1111",
            additionalDetails: ["error": AnyCodable("Insufficient funds")],
            gatewayTransactionResponse: .declinedGatewayTransactionResponse,
            processorResponseCode: "51",
            processorResponseMessage: "Insufficient funds",
            transactionType: "sale",
            appleTransactionId: nil,
            readerIdentifier: "reader_decline",
            surchargeDisclosure: nil,
            surchargeAllowed: nil,
            surchargePercentage: nil
        )
    }

    public static var mockRefundedTransction: KoardTransaction {
        .init(
            transactionId: "txn_refunded_002",
            eventId: "event_refunded_xyz",
            mid: "mid_refund",
            tid: "tid_refund",
            processorMid: "proc_mid_refund",
            processorTid: "proc_tid_refund",
            accountId: "acct_refund",
            deviceId: "device_refund",
            processor: "Stripe",
            gateway: "RefundGateway",
            currency: "USD",
            locationId: "loc_refund",
            gatewayTransactionId: "gw_refund_002",
            subtotal: 2000,
            tipAmount: 400,
            tipType: .fixed,
            taxAmount: 160,
            taxRate: 8,
            totalAmount: 2560,
            surchargeApplied: true,
            surchargeAmount: 40,
            surchargeRate: 2.0,
            refunded: 2560,
            reversed: 0,
            ownerId: "owner_refund",
            parentAccountIds: ["parentX", "parentY"],
            createdAt: Int(Date().timeIntervalSince1970 * 1000) - 7200000,
            status: .refunded,
            statusReason: "Full refund issued",
            paymentMethod: "card",
            cardType: "credit",
            cardBrand: "Visa",
            card: "**** 5678",
            additionalDetails: ["refundReason": AnyCodable("Customer returned item")],
            gatewayTransactionResponse: .refundedGatewayTransactionResponse,
            processorResponseCode: "00",
            processorResponseMessage: "Approved",
            transactionType: "refund",
            appleTransactionId: "apple_txn_refund_002",
            readerIdentifier: "reader_refunded",
            surchargeDisclosure: "2% surcharge refunded",
            surchargeAllowed: true,
            surchargePercentage: 2.0
        )
    }
}

